### ISSUE TITLE
Multiple controllers

### ISSUE THREAD

**Issue by pbywater** [ArturSpirin/pyPS4Controller#10]
Hi Artur,

Thanks so much for this repo - working really well for me!

I'm trying to connect multiple controllers and was wondering if that was supported and, if so, how I might do this?

**Comment by ArturSpirin** [comment]
@pbywater yes, it should work with multiple controllers like this
```py
controller1 = MyController(interface="/dev/input/js0")
controller2 = MyController(interface="/dev/input/js1")
```
