### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by MasterLomb** [ArturSpirin/pyPS4Controller#17]
Hello Artur, 

Thank you for writing this code. I am planning to make a remote controlled tank for my kid as my first raspberry control project. To get it to work, I was first trying to get the PS4 controller hooked up. Unfortunately I am getting an error ->

In the attachment you can see I am running the ds4drv.
I copied one of the simple codes to start testing but the same error comes back with each set of code
on the bottom screen you can see the exact error I am getting

Doing some research suggested to run the code from the root by using "sudo" but this gave the same error. 

Hope you can help!

Karel
![ds4drv issue](https://user-images.githubusercontent.com/74499649/99188238-eb9c5b80-2728-11eb-90df-48b0d0b9e8b0.PNG)

**Comment by iwanimsand** [comment]
@MasterLomb What happens if you run your code with:
```
python3 test.py
# or
sudo python3 test.py
```
?

**Comment by salamwaddah** [comment]
Same issue here.
Python 2.7.16
Raspberry Pi 4

Solution for me was `pip3 install pyPS4Controller` and did `python3 test.py`

**Comment by ArturSpirin** [comment]
@salamwaddah @MasterLomb This issue should be fixed in version 1.2.4
