### ISSUE TITLE
"value" is different from raw data

### ISSUE THREAD

**Issue by ryo-a** [ArturSpirin/pyPS4Controller#20]
Hi, thank you for such a nice library.

I'm testing the Dual Shock 4 and this library with Raspberry Pi 4 but I have a problem,
When I move sticks on DS4, the `value` seems wrong.

I tried to turn on the debug mode, the "value" in raw data seems correct but returned `value` is still wrong.
How should I fix it?

```
button_id: 3 button_type: 2 value: 20944 overflow: (20944, 2, 3)
on_R3_right: 30
button_id: 4 button_type: 2 value: -32767 overflow: (-32767, 2, 4)
on_R3_up: 30
button_id: 3 button_type: 2 value: 18579 overflow: (18579, 2, 3)
on_R3_right: 30
button_id: 3 button_type: 2 value: -4054 overflow: (-4054, 2, 3)
on_R3_left: 30
button_id: 3 button_type: 2 value: -31417 overflow: (-31417, 2, 3)
on_R3_left: 30
button_id: 4 button_type: 2 value: -7770 overflow: (-7770, 2, 4)
on_R3_up: 30
button_id: 3 button_type: 2 value: -32093 overflow: (-32093, 2, 3)
on_R3_left: 30
button_id: 4 button_type: 2 value: -5743 overflow: (-5743, 2, 4)
on_R3_up: 30
button_id: 3 button_type: 2 value: -32767 overflow: (-32767, 2, 3)
on_R3_left: 30
button_id: 4 button_type: 2 value: 2702 overflow: (2702, 2, 4)
on_R3_down: 30
button_id: 4 button_type: 2 value: 3378 overflow: (3378, 2, 4)
on_R3_down: 30
button_id: 4 button_type: 2 value: 9796 overflow: (9796, 2, 4)
on_R3_down: 30
button_id: 3 button_type: 2 value: -16216 overflow: (-16216, 2, 3)
on_R3_left: 30
button_id: 4 button_type: 2 value: 1013 overflow: (1013, 2, 4)
on_R3_down: 30
button_id: 3 button_type: 2 value: -14527 overflow: (-14527, 2, 3)
on_R3_left: 30
button_id: 4 button_type: 2 value: 0 overflow: (0, 2, 4)
on_R3_y_at_rest
button_id: 3 button_type: 2 value: -3716 overflow: (-3716, 2, 3)
on_R3_left: 30
button_id: 3 button_type: 2 value: 0 overflow: (0, 2, 3)
on_R3_x_at_rest
button_id: 3 button_type: 2 value: -1014 overflow: (-1014, 2, 3)
on_R3_left: 30
button_id: 3 button_type: 2 value: -2365 overflow: (-2365, 2, 3)
on_R3_left: 30
button_id: 3 button_type: 2 value: -32767 overflow: (-32767, 2, 3)
on_R3_left: 30
button_id: 3 button_type: 2 value: 0 overflow: (0, 2, 3)
on_R3_x_at_rest
button_id: 3 button_type: 2 value: -32767 overflow: (-32767, 2, 3)
on_R3_left: 30
button_id: 3 button_type: 2 value: 0 overflow: (0, 2, 3)
on_R3_x_at_rest
```

### environment

Running on Raspberry Pi 4 and Raspbian GNU/Linux 10 (buster)
I connect DS4 via bluetooth (with `bluetoothctl`)

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by ryo-a** [comment]
FYI: it runnning properly in version 1.2.3 like below

```
on_R2_press: 31078
on_R2_press: 32767
on_R2_press: 29727
on_R2_press: 28376
on_R2_press: 3040
on_R2_press: 1351
on_R2_press: -8784
on_R2_press: -9459
on_R2_release
on_R2_press: -11486
on_R2_press: -10473
on_R2_press: 0
on_R2_press: 11147
on_R2_press: 11823
on_R2_press: 22633
on_R2_press: 22971
on_R2_press: 29727
on_R2_press: 30065
on_R2_press: 32767
on_R2_press: 2702
on_R2_press: 337
on_R2_press: -29053
on_R2_release
on_R2_press: 32767
on_R2_press: 27362
on_R2_press: 21620
on_R2_press: 13512
on_R2_press: 6080
on_R2_press: 0
on_R2_press: -3716
on_R2_press: -10473
on_R2_press: -16891
on_R2_press: -23310
on_R2_press: -30066
```

**Comment by sabin-roman** [comment]
Same issue here, could you please help with a fix..

**Comment by ArturSpirin** [comment]
@ryo-a @sabin-roman If its running properly on version 1.2.3 - please change the event_format to "LhBB". There were some minor changes done to re-map buttons based on format and default format was changed from LhBB to 3Bh2b. Please let me know if it fixes your issue.

**Comment by sabin-roman** [comment]
Hi Artur, thanks for the quick reply and hint. I have changed the format to LhBB, however now, the overwritten events do not fire anymore: 

`from pyPS4Controller.controller import Controller

class MyController(Controller):  

    def on_L3_up(self, value):
        print("on_L3_up: ", value)

    def on_L3_down(self, value):
        print("on_L3_down: ", value)

    def on_L3_left(self, value):
        print("on_L3_left: ", value)

    def on_L3_right(self, value):
        print("on_L3_right: ", value)

controller = MyController(interface="/dev/input/js2", event_format="LhBB")
controller.debug = False
controller.listen()`

**Comment by DomNovak** [comment]
Hi, I am having some trouble with the stick position as well. When I use the basic example code I always get the same value (usually something between 170 to 190) for the stick position no matter if I use the left or the right stick or going up down left or right. As I am quite new to this topic I also don't know how to use the debug mode. Any advice would be greatly appreciated.

**Comment by sabin-roman** [comment]
Bumping this issue up a bit, as the library is quite not usable without this fix ..  I tried to look through the code changes for the last release, but could not figure out a fix.

Artur, if you have some time to give this a look, it would be great.

**Comment by thavens** [comment]
overflow is a list containing 3 values that is unpacked with struct. value should actually be overflow[0].
inserting `value = overflow[0]` after unpacking will correct the issue with value. 

`def unpack():
    __event = struct.unpack(self.event_format, event)
    return (__event[3:], __event[2], __event[1], __event[0])

(overflow, value, button_type, button_id) = unpack()`

**Comment by DomNovak** [comment]
@thavens thank you for this clue!
Could you maybe explain how to use this? At which point of the code should I insert value = overflow[0]?  (I am very new to OOP and python)

**Comment by pragmaDave** [comment]
That solved the issue for me. Thanks @thavens!

@DomNovak, You have to edit the python file, "controller.py" which is in the directory, "pyPS4Controller". This directory is in a site-packages directory on my linux mint machine.

I followed thavens suggestion by placing the following code: `value = overflow[0]` just below the line, `(overflow, value, button_type, button_id) = unpack()`

So the final modified code (snippet) in controller.py would be:

` ... code above`
<pre>while not self.stop and event:
     (overflow, value, button_type, button_id) = unpack()
      value = overflow[0] # **this is the new line **
      if button_id not in self.black_listed_buttons:</pre>
` ... code continues`

Hope this helps!

**Comment by DomNovak** [comment]
@pragmaDave thank you so much, now it works :)

**Comment by williamledda** [comment]
@thavens, I think that by overwriting the `value` with `overflow[0]`, would brake the `event_format == "LhBB"`.

A more safe solution would be to get the value directly from the `event_definition`, after it has been processed. So I suggest to replace all plain `value` with `event.value` in the `__handle_event` method.

I.e.

```
    def __handle_event(self, button_id, button_type, value, overflow, debug):

        event = self.event_definition(button_id=button_id,
                                      button_type=button_type,
                                      value=value,
                                      connecting_using_ds4drv=self.connecting_using_ds4drv,
                                      overflow=overflow,
                                      debug=debug)

        if event.R3_event():
            self.event_history.append("right_joystick")
            if event.R3_y_at_rest():
                self.on_R3_y_at_rest()
            elif event.R3_x_at_rest():
                self.on_R3_x_at_rest()
            elif event.R3_right():
                self.on_R3_right(event.value)
            elif event.R3_left():
                self.on_R3_left(event.value)
            elif event.R3_up():
                self.on_R3_up(event.value)
            elif event.R3_down():
                self.on_R3_down(event.value)
...

**Comment by sabin-roman** [comment]
@ArturSpirin since with this fix, we have a stable version, it would be nice if you could bump to v.1.2.5.

**Comment by ArturSpirin** [comment]
@williamledda Thanks a lot for fixing this bug!
1.2.5 pushed to Pypi. 
Closing this.

**Comment by williamledda** [comment]
@ArturSpirin thank you for this great library 👍
