### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by rpi-james** [ArturSpirin/pyPS4Controller#23]
When I try to run the code you provide here on the Github, I get a ModuleNotFoundError: No module named 'pyPS4Controller'.
Have you run into this issue? Do I need to move the files to another location so the RPi can see them? I'm quite lost over this.
Thank you!

**Comment by ArturSpirin** [comment]
It sounds like you may have multiple Python versions installed on your RPi, you may have installed the module for one of them but using another one to run the program.

**Comment by rpi-james** [comment]
I'll take a look at that. Does it only work in the command terminal or should it also work in a script?

**Comment by ArturSpirin** [comment]
It should work in any Python script as well.

**Comment by rpi-james** [comment]
Looks Like my Pi is version 3.7.3. Does this code still work? Just checking. Thank You for your help.

**Comment by rpi-james** [comment]
Thanks for your help Artur. I got it working well(installed for the wrong version) and can move forward with my project. Great work on this code!
