### ISSUE TITLE
Button Press Are Outputting Wrong symbol

### ISSUE THREAD

**Issue by couryrr** [ArturSpirin/pyPS4Controller#3]
It does not impact what I am working on but pressing the cross shows square on my cli and then everything is off by one. I can do a pull request to adjust this if it is a real problem.

**Comment by ArturSpirin** [comment]
@couryrr Please see issue #1 - The Event class was pushed in order to create custom mapping as it seems like button mapping may not match between different environments. Check docs for https://github.com/ArturSpirin/pyPS4Controller#overloading-event-detection on how to use it.
