### ISSUE TITLE
Non-Blocking Usage of the Controller

### ISSUE THREAD

**Issue by irmakguzey** [ArturSpirin/pyPS4Controller#39]
Hello, 
I am trying to use the controller in a non-blocking manner. 
Currently the method `listen()` is a blocking call. The whole program basically starts waiting for input when we run `listen()` and it basically doesn't continue running.  
Even though the controller and the library could be really useful for me, I definitely need a library that is unblocking.
Am I missing something? Is there a way to use the library without making it block the main process? If not, is there a way to run the class in a separate process and somehow get class members from that process? (Simpler way than classic Python approaches which can end up being quite complicated). 

Thank you very much! 
Irmak.

**Comment by ArturSpirin** [comment]
@irmakguzey You can run listen() in another thread and do you r other operations in the main thread.
