### ISSUE TITLE
trigger event connect/disconnect

### ISSUE THREAD

**Issue by KrifaYounes** [ArturSpirin/pyPS4Controller#7]
Hello,
I want to send a signal to my mobile application to know if the ps4 controller has started or has disconnected without touching any button.
is there a trigger that lets you know?

**Comment by ArturSpirin** [comment]
Hi @KrifaYounes ,
There is currently no such triggers but it can be easily added I think. I'll convert this into a feature request and see what I can do.

**Comment by ArturSpirin** [comment]
@KrifaYounes Try it now in version pyPS4Controller 1.1.9 and let me know. I've also added how to use it here https://github.com/ArturSpirin/pyPS4Controller#registering-callbacks

**Comment by KrifaYounes** [comment]
Ok thanks i will try

**Comment by KrifaYounes** [comment]
it work fine
thanks a lot
