### ISSUE TITLE
listening can't be stopped

### ISSUE THREAD

**Issue by mhaj98** [ArturSpirin/pyPS4Controller#9]
Hello, 

I wanted to overload the Controller press button to stop listening in order to continue analyzing the data collected. I set the stop to True; however, it continued handling events.

I had a look at your code and detected that in the listening function of your controller:
```
        wait_for_interface()
        while not self.stop:
            try:
                _file = open(self.interface, "rb")
                event = read_events()
                while event:
                    (*tv_sec, value, button_type, button_id) = struct.unpack(self.event_format, event)
                    if self.debug:
                        print("button_id: {} button_type: {} value: {}".format(button_id, button_type, value))
                    if button_id not in self.black_listed_buttons:
                        self.__handle_event(button_id=button_id, button_type=button_type, value=value)
                    event = read_events()
                    
            except KeyboardInterrupt:
                print("\nExiting (Ctrl + C)")
                on_disconnect_callback()
                exit(1)
```
This will lead to enter the main while loop only once since the event is never false.
I would recommend to add the external condition in the loop inside (line 429):
` while (event and (not self.stop)):`

This solved my problem

**Comment by ArturSpirin** [comment]
@mhaj98 Hey thanks for spotting that issue.
